# Generated by Django 2.1.11 on 2019-11-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20191021_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='show_document_metadata',
            field=models.BooleanField(default=False),
        ),
    ]
